.deploy:
  stage: deploy
  only:
    changes:
    - environments/**/*
    refs:
    - main
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  image:
    name: harbor.peinser.com/dockerhub/alpine/k8s:1.28.4
  before_script:
  - kubectl config use-context peinser/agents:main
  - kubectl config set-context --current --namespace=$CI_ENVIRONMENT_SLUG-$CI_K8S_NAMESPACE
  - cd environments/$CI_ENVIRONMENT_SLUG
  script:
  - envsubst < values.yaml > generated.yaml
  - mv generated.yaml values.yaml
  - cat values.yaml
  - helm dependency update
  - helm upgrade --install $CI_ENVIRONMENT_SLUG .

deploy_sample:
  extends: .deploy
  only:
    changes:
    - environments/sample/**
  environment:
    name: sample